
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Simple helper to expand variables like ${VAR} or ${{VAR}} in environment variables
function expandEnvVars(value: string | undefined): string | undefined {
  if (!value) return value;
  return value.replace(/\$\{(?:\{(\w+)\}|(\w+))\}/g, (_, g1, g2) => {
    const name = g1 || g2;
    return process.env[name] || "";
  });
}

// Check if the current command is for deployment/migration deploy
const isDeploy = process.argv.includes("deploy") || process.argv.includes("status");

const rawDatabaseUrl = (isDeploy && (process.env.DATABASE_PUBLISH_URL || process.env.DATABASE_PUBLIC_URL))
  || env("DATABASE_URL");

const databaseUrl = expandEnvVars(rawDatabaseUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
