
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Check if the current command is for deployment/migration deploy
const isDeploy = process.argv.includes("deploy") || process.argv.includes("status");

// const databaseUrl = (isDeploy && (process.env.DATABASE_PUBLISH_URL || process.env.DATABASE_PUBLIC_URL))
//   || env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
